# Sizing and Positioning
WINDOW_WIDTH = 0
WINDOW_HEIGHT = 0
CANVAS_WIDTH = 0
CANVAS_HEIGHT = 0
PADDING = 2.5

# Typography
FONT_FAMILY = "Arial"
FONT_SIZE = 12

# Canvas
TILE_SIZE = 32
LINE_WIDTH = 3
DOT_RADIUS = 5

# Color
CURSOR_COLOR = "#000000"
START_POINT_COLOR = "#16a34a"
END_POINT_COLOR = "#dc2626"
GRID_COLOR = "#d4d4d4"
PATH_COLOR = "#facc15"
MAP_COLOR = "#2563eb"
PREVIEW_COLOR = "#475569"
MAP_FILL_COLOR = "#ddeeff"
